emailhub/runtests/urls.py
# -*- coding: utf-8 -*-
"""
EmailHub tests urls
"""
from django.conf.urls import url, include
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('emailhub.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

# Add media and static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emailhub/urls.py
# -*- coding: utf-8 -*-
"""
EmailHub core URLs
"""
from django.conf.urls import url

from emailhub.views import (
    InboxListView, EmailMessageDetailView, EmailMessageUpdateView,
    process_message,
)

app_name = 'emailhub'  # pylint: disable=C0103
urlpatterns = [  # pylint: disable=C0103

    # Email messages list view
    url(r'^$', InboxListView.as_view(),
        name='emailmessage_list'),

    # Email messages detail view
    url(r'^(?P<pk>[^/]+)/$', EmailMessageDetailView.as_view(),
        name='emailmessage_detail'),

    # Email messages update view
    url(r'^(?P<pk>[^/]+)/edit/$', EmailMessageUpdateView.as_view(),
        name='emailmessage_update'),

    url(r'^process/(?P<pk>[0-9]+)/(?P<action>\w+)/$', process_message,
        name='emailmessage_process'),

]

emailhub/templates/emailhub/base.html
{% extends "base.html" %}

emailhub/templates/emailhub/ckeditor.inc.html
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}
{# To generate a toolbar config head to: /static/emailhub/ckeditor/samples/toolbarconfigurator/index.html#basic #}
<script src="{% static "emailhub/ckeditor/ckeditor.js" %}"></script>
<script src="{% static "emailhub/js/jquery.emailhubEditor.js" %}"></script>
<link href="{% static "emailhub/ckeditor/skins/minimalist/editor.css" %}" rel="stylesheet">
<script>
(function($) {
  $(function(){
    $('#emailhub-emailmessage-editor').emailhubEditor({
      language: '{{ LANGUAGE_CODE|lower }}',
      messages: {
        save_error: '{% trans "An error occured while saving document, please check the console." %}',
        html_changed_confirm: '{% trans "The HTML version has changed, but not the text version. Are you sure you want to save this message ?" %}',
        text_changed_confirm: '{% trans "The text version has changed, but not the HTML version. Are you sure you want to save this message ?" %}'
      }
    });
  });
}(jQuery));
</script>

emailhub/templates/emailhub/emailmessage_detail.html
{% extends "emailhub/base.html" %}

{% block content %}
<div class="content">
  <div class="row">
    <div class="col s12">
      <h1>{{ object.subject }}</h1>
      <p>From: {{ object.email_from|urlize }}</p>
      <p>To: {{ object.to|urlize}}</p>
      <p>Date: {{ object.date_created|date }}</p>
      <pre>{{ object.body_text|urlize }}</pre>
    </div>
  </div>
</div>
{% endblock %}

emailhub/templates/emailhub/emailmessage_list.html
{% extends "emailhub/base.html" %}
{% load i18n %}

{% block content %}
<div class="content">
  <div class="row">
    <div class="col s12">
      <h1>{% trans "Inbox" %}</h1>
      {% include "emailhub/emailmessage_list.inc.html" %}
      {% include "emailhub/pagination.inc.html" %}
    </div>
  </div>
</div>
{% endblock %}

emailhub/templates/emailhub/emailmessage_list.inc.html
<ul class="collection">
  {% for object in object_list %}
  <li class="collection-item">
    <span class="badge" data-badge-caption="{{ object.date_sent }}"></span>
    <a href="{% if request.user.is_superuser and object.is_draft %}{{ object.get_update_url }}{% else %}{{ object.get_absolute_url }}{% endif %}">
      <b>{{ object.subject }}</b>
    </a>
  </li>
  {% endfor %}
</ul>

emailhub/templates/emailhub/emailmessage_update.html
{% extends "emailhub/base.html" %}
{% load i18n %}

{% block extrahead %}{{ block.super }}
{% include "emailhub/ckeditor.inc.html" %}
{% endblock %}

{% block content %}
<div class="content">
  <div class="row">
    <div class="col s12">
      <div id="emailhub-emailmessage-editor" class="card">
        <div class="card-title">
          <div class="title-actions">
            {# PREV #}
            {% if object.get_previous_by_created or object.get_next_by_created %}
              {% if object.get_previous_by_created and object.get_previous_by_created.customer %}
              <a href="{{ object.get_previous_by_created.get_absolute_url }}" class="btn" data-turbolinks="false"><i class="material-icons left">chevron_left</i> {% trans "Prev" %}</a>
              {% endif %}
              {# NEXT #}
              {% if object.get_next_by_created and object.get_next_by_created.customer %}
              <a href="{{ object.get_next_by_created.get_absolute_url }}" class="btn" data-turbolinks="false"><i class="material-icons right">chevron_right</i> {% trans "Next" %}</a>
              {% endif %}
            {% endif %}
            {# SAVE #}
            {% if object.is_draft %}
            {# DELETTE #}
            <a href="{% url "emailhub:emailmessage_process" pk=object.pk action="delete" %}" id="emailhub-emailmessage-delete" class="btn tooltip red" data-tooltip="{% trans "Delete" %}" data-turbolinks="false">
              <i class="material-icons">delete_forever</i>
            </a>
            {# SAVE #}
            <a href="{% url "emailhub:emailmessage_process" pk=object.pk action="save" %}" id="emailhub-emailmessage-save" class="btn tooltip blue disabled" data-tooltip="{% trans "Save" %}" data-turbolinks="false">
              <i class="material-icons">save</i>
            </a>
            {# SEND #}
            <a href="{% url "emailhub:emailmessage_process" pk=object.pk action="send" %}" id="emailhub-emailmessage-send" class="btn tooltip green" data-tooltip="{% trans "Send" %}" data-turbolinks="false" data-confirm="{% trans "Are you sure you want to send this message ?" %}">
              <i class="material-icons">send</i>
            </a>
            {% endif %}
            {# ADMIN #}
            <a href="{% url "admin:emailhub_emailmessage_change" object.pk as admin_url %}" id="emailhub-emailmessage-admin" class="btn tooltip" data-tooltip="{% trans "Open in admin" %}" data-turbolinks="false">
              <i class="material-icons">settings</i>
            </a>
          </div>
          <h5>
            <i class="material-icons blue-text">email</i> <span class="blue-text">{{ object.subject }}</span>
            <span class="badge white-text blue">{% trans "Draft" %}</span>
            <span class="badge white-text orange message-modified hide">{% trans "Modified, don't forget to save!" %}</span>
          </h5>
        </div>
        <div class="card-content">
          <hr>
          <div class="email-meta">
            <strong>{% trans "To" %}</strong> {{ object.to_email|urlize }}
            &ndash;
            <strong>{% trans "From" %}</strong> {{ object.from_email }}
          </div>
          <hr>
          {% if object.send_error %}
          <div class="alert alert-error">
            {{ object.send_error }}
          </div>
          {% endif %}

          <ul class="tabs messaging-tabs">
            {#<li class="tab"><a href="#tab-preview">{% trans "Preview" %}</a></li>#}
            <li class="tab html"><a href="#tab-html">{% trans "HTML" %}</a></li>
            <li class="tab text"><a href="#tab-text">{% trans "Text" %}</a></li>
          </ul>
          <br>
          {% comment %}
          <div id="tab-preview" class="messaging-editor-tab">
            {{ object.body_html|safe }}
          </div>
          {% endcomment %}
          <div id="tab-html" class="messaging-editor-tab">
            <textarea id="emailhub-emailmessage-body-html">{{ object.body_html }}</textarea>
          </div>
          <div id="tab-text" class="messaging-editor-tab">
            <textarea id="emailhub-emailmessage-body-text">{{ object.body_text }}</textarea>
          </div>
          <div class="clear"></div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

emailhub/templates/emailhub/inbox.html
{% extends "emailhub/base.html" %}

{% block content %}
<h1>Email Inbox</h1>
<ul>
  {% for object in object_list %}
  <li>{{ object.date_created|date }} - {{ object.subject|title }}</li>
  {% empty %}
  <li>No email yet.</li>
  {% endfor %}
</ul>
{% endblock %}

emailhub/templates/emailhub/pagination.inc.html
{% if is_paginated %}
<ul class="pagination center">
  {# PREV #}
  {% if page_obj.has_previous %}
    <li>
      <a href="?page={{ page_obj.previous_page_number }}">
        <i class="material-icons">chevron_left</i>
      </a>
    </li>
  {% else %}
    <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
  {% endif %}
  {# PAGES #}
  {% for page in paginator.page_range %}
    <li {% if page == page_obj.number %}class="active"{% endif %}>
      <a href="?page={{ page }}">{{ page }}</a>
    </li>
  {% endfor %}
  {# NEXT #}
  {% if page_obj.has_next %}
    <li>
      <a href="?page={{ page_obj.next_page_number }}">
        <i class="material-icons">chevron_right</i>
      </a>
    </li>
  {% else %}
    <li class="disabled">
      <a href="#!">
        <i class="material-icons">chevron_right</i>
      </a>
    </li>
  {% endif %}
</ul>
{% endif %}